[2024-03-11T15:40:35.789+0000] {processor.py:161} INFO - Started process (PID=523) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:40:35.790+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:40:35.791+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:40:35.791+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:40:35.795+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:40:35.795+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:40:35.796+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:40:35.795+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:40:35.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:40:35.807+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T15:41:29.744+0000] {processor.py:161} INFO - Started process (PID=587) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:41:29.747+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:41:29.748+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:41:29.747+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:41:29.751+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:41:29.751+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:41:29.752+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:41:29.751+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:41:29.752+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:41:29.762+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T15:42:23.053+0000] {processor.py:161} INFO - Started process (PID=642) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:42:23.055+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:42:23.056+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:42:23.055+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:42:23.059+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:42:23.059+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:42:23.060+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:42:23.059+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:42:23.060+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:42:23.070+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T15:43:23.452+0000] {processor.py:161} INFO - Started process (PID=700) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:43:23.454+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:43:23.455+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:43:23.455+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:43:23.459+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:43:23.459+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:43:23.459+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:43:23.459+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:43:23.460+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:43:23.471+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T15:44:22.752+0000] {processor.py:161} INFO - Started process (PID=757) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:44:22.756+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:44:22.757+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:44:22.757+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:44:22.761+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:44:22.760+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:44:22.761+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:44:22.761+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:44:22.761+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:44:22.774+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-03-11T15:45:16.786+0000] {processor.py:161} INFO - Started process (PID=812) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:45:16.788+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:45:16.789+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:45:16.789+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:45:16.793+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:45:16.792+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:45:16.793+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:45:16.793+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:45:16.793+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:45:16.806+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-11T15:46:07.936+0000] {processor.py:161} INFO - Started process (PID=860) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:46:07.938+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:46:07.939+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:46:07.939+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:46:07.943+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:46:07.943+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:46:07.943+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:46:07.943+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:46:07.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:46:07.954+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T15:47:10.790+0000] {processor.py:161} INFO - Started process (PID=920) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:47:10.793+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:47:10.794+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:47:10.794+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:47:10.799+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:47:10.798+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:47:10.799+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:47:10.799+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:47:10.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:47:10.810+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-03-11T15:48:09.009+0000] {processor.py:161} INFO - Started process (PID=977) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:48:09.011+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:48:09.012+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:48:09.011+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:48:09.015+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:48:09.015+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:48:09.016+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:48:09.016+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:48:09.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:48:09.027+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T15:49:10.147+0000] {processor.py:161} INFO - Started process (PID=1035) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:49:10.149+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:49:10.150+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:49:10.150+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:49:10.155+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:49:10.154+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:49:10.155+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:49:10.155+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:49:10.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:49:10.166+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T15:50:18.999+0000] {processor.py:161} INFO - Started process (PID=1100) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:50:19.001+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:50:19.002+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:50:19.002+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:50:19.006+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:50:19.005+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:50:19.006+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:50:19.006+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:50:19.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:50:19.018+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T15:51:30.267+0000] {processor.py:161} INFO - Started process (PID=1186) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:51:30.269+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:51:30.270+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:51:30.269+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:51:30.273+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:51:30.272+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:51:30.273+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:51:30.273+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:51:30.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:51:30.283+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-03-11T15:52:32.336+0000] {processor.py:161} INFO - Started process (PID=1250) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:52:32.338+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:52:32.339+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:52:32.339+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:52:32.343+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:52:32.342+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:52:32.343+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:52:32.343+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:52:32.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:52:32.354+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T15:53:22.977+0000] {processor.py:161} INFO - Started process (PID=1299) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:53:22.979+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:53:22.981+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:53:22.980+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:53:22.985+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:53:22.985+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:53:22.985+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:53:22.985+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:53:22.986+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:53:22.996+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T15:54:36.707+0000] {processor.py:161} INFO - Started process (PID=1390) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:54:36.709+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:54:36.710+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:54:36.710+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:54:36.714+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:54:36.713+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:54:36.714+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:54:36.714+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:54:36.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:54:36.725+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T15:56:10.623+0000] {processor.py:161} INFO - Started process (PID=1481) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:56:10.625+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:56:10.626+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:56:10.625+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:56:10.629+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:56:10.629+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:56:10.630+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:56:10.629+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:56:10.630+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:56:10.641+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T15:57:06.362+0000] {processor.py:161} INFO - Started process (PID=1533) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:57:06.365+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:57:06.366+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:57:06.365+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:57:06.369+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:57:06.369+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:57:06.369+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:57:06.369+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:57:06.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:57:06.380+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T15:58:00.709+0000] {processor.py:161} INFO - Started process (PID=1585) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:58:00.711+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T15:58:00.712+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:58:00.711+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:58:00.716+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:58:00.715+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T15:58:00.716+0000] {logging_mixin.py:188} INFO - [2024-03-11T15:58:00.716+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T15:58:00.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T15:58:00.727+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T16:09:05.364+0000] {processor.py:161} INFO - Started process (PID=456) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:09:05.367+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:09:05.368+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:09:05.367+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:09:05.371+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:09:05.371+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:09:05.372+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:09:05.371+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:09:05.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:09:05.382+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T16:10:00.142+0000] {processor.py:161} INFO - Started process (PID=509) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:10:00.144+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:10:00.145+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:10:00.144+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:10:00.149+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:10:00.148+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:10:00.149+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:10:00.149+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:10:00.149+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:10:00.161+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T16:10:53.378+0000] {processor.py:161} INFO - Started process (PID=562) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:10:53.380+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:10:53.381+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:10:53.380+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:10:53.385+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:10:53.384+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:10:53.386+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:10:53.385+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:10:53.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:10:53.397+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T16:11:50.617+0000] {processor.py:161} INFO - Started process (PID=625) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:11:50.618+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:11:50.619+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:11:50.619+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:11:50.623+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:11:50.622+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:11:50.623+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:11:50.623+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:11:50.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:11:50.634+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T16:12:44.995+0000] {processor.py:161} INFO - Started process (PID=678) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:12:44.997+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:12:44.998+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:12:44.998+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:12:45.002+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:12:45.001+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:12:45.002+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:12:45.002+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:12:45.002+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:12:45.014+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T16:13:53.106+0000] {processor.py:161} INFO - Started process (PID=761) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:13:53.108+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:13:53.109+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:13:53.108+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:13:53.112+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:13:53.112+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:13:53.113+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:13:53.113+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:13:53.113+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:13:53.125+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T16:14:46.202+0000] {processor.py:161} INFO - Started process (PID=814) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:14:46.204+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:14:46.205+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:14:46.205+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:14:46.210+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:14:46.208+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:14:46.211+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:14:46.210+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:14:46.211+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:14:46.221+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T16:15:56.249+0000] {processor.py:161} INFO - Started process (PID=885) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:15:56.252+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:15:56.253+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:15:56.252+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:15:56.256+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:15:56.256+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:15:56.257+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:15:56.256+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:15:56.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:15:56.269+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T16:17:05.941+0000] {processor.py:161} INFO - Started process (PID=954) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:17:05.944+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:17:05.945+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:17:05.944+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:17:05.949+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:17:05.948+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:17:05.950+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:17:05.949+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:17:05.950+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:17:05.960+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T16:18:18.300+0000] {processor.py:161} INFO - Started process (PID=1025) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:18:18.302+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:18:18.303+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:18:18.303+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:18:18.307+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:18:18.306+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:18:18.307+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:18:18.307+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:18:18.307+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:18:18.318+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T16:19:41.409+0000] {processor.py:161} INFO - Started process (PID=1111) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:19:41.411+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:19:41.412+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:19:41.412+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:19:41.416+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:19:41.415+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:19:41.417+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:19:41.417+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:19:41.417+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:19:41.428+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-03-11T16:20:34.070+0000] {processor.py:161} INFO - Started process (PID=1188) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:20:34.072+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:20:34.073+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:20:34.073+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:20:34.078+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:20:34.076+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:20:34.078+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:20:34.078+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:20:34.079+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:20:34.089+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T16:21:22.547+0000] {processor.py:161} INFO - Started process (PID=1261) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:21:22.550+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:21:22.551+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:21:22.550+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:21:22.554+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:21:22.554+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:21:22.555+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:21:22.554+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:21:22.555+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:21:22.565+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T16:22:54.281+0000] {processor.py:161} INFO - Started process (PID=1379) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:22:54.283+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:22:54.284+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:22:54.284+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:22:54.288+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:22:54.287+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:22:54.288+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:22:54.288+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:22:54.288+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:22:54.301+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-11T16:24:06.253+0000] {processor.py:161} INFO - Started process (PID=1461) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:24:06.255+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:24:06.256+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:24:06.255+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:24:06.260+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:24:06.260+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:24:06.260+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:24:06.260+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:24:06.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:24:06.271+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T16:24:59.982+0000] {processor.py:161} INFO - Started process (PID=1512) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:24:59.984+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:24:59.985+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:24:59.984+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:24:59.990+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:24:59.988+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:24:59.991+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:24:59.991+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:24:59.991+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:25:00.002+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-03-11T16:27:33.287+0000] {processor.py:161} INFO - Started process (PID=1604) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:27:33.295+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:27:33.296+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:27:33.295+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:27:33.301+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:27:33.300+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:27:33.301+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:27:33.301+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:27:33.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:27:33.313+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-03-11T16:28:25.414+0000] {processor.py:161} INFO - Started process (PID=1663) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:28:25.423+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:28:25.424+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:28:25.423+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:28:25.428+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:28:25.428+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:28:25.428+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:28:25.428+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:28:25.429+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:28:25.439+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-03-11T16:29:27.925+0000] {processor.py:161} INFO - Started process (PID=1728) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:29:27.927+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:29:27.929+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:29:27.928+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:29:27.933+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:29:27.932+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:29:27.933+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:29:27.933+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:29:27.933+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:29:27.944+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-11T16:30:22.842+0000] {processor.py:161} INFO - Started process (PID=1789) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:30:22.847+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:30:22.848+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:30:22.848+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:30:22.853+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:30:22.852+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:30:22.853+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:30:22.853+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:30:22.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:30:22.868+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-03-11T16:31:53.957+0000] {processor.py:161} INFO - Started process (PID=1867) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:31:53.959+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:31:53.960+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:31:53.960+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:31:53.963+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:31:53.963+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:31:53.963+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:31:53.963+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:31:53.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:31:53.972+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-03-11T16:33:34.217+0000] {processor.py:161} INFO - Started process (PID=1916) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:33:34.220+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:33:34.221+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:33:34.221+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:33:34.225+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:33:34.225+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:33:34.226+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:33:34.225+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:33:34.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:33:34.237+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-11T16:36:22.325+0000] {processor.py:161} INFO - Started process (PID=2009) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:36:22.327+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:36:22.328+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:36:22.328+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:36:22.334+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:36:22.333+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:36:22.334+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:36:22.334+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:36:22.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:36:22.346+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-03-11T16:41:20.858+0000] {processor.py:161} INFO - Started process (PID=449) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:41:20.860+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:41:20.861+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:41:20.860+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:41:20.864+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:41:20.864+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:41:20.864+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:41:20.864+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:41:20.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:41:20.874+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-03-11T16:44:42.941+0000] {processor.py:161} INFO - Started process (PID=674) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:44:42.943+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:44:42.944+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:44:42.944+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:44:42.948+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:44:42.947+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:44:42.948+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:44:42.948+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:44:42.948+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:44:42.959+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T16:48:01.054+0000] {processor.py:161} INFO - Started process (PID=822) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:48:01.057+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:48:01.058+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:48:01.057+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:48:01.061+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:48:01.060+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:48:01.061+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:48:01.061+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:48:01.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:48:01.071+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-03-11T16:48:58.387+0000] {processor.py:161} INFO - Started process (PID=930) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:48:58.389+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:48:58.390+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:48:58.389+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:48:58.393+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:48:58.393+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:48:58.394+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:48:58.394+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:48:58.394+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:48:58.404+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T16:49:52.317+0000] {processor.py:161} INFO - Started process (PID=1022) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:49:52.319+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:49:52.320+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:49:52.319+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:49:52.323+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:49:52.323+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:49:52.324+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:49:52.324+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:49:52.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:49:52.335+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T16:50:47.419+0000] {processor.py:161} INFO - Started process (PID=1092) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:50:47.421+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:50:47.422+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:50:47.422+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:50:47.427+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:50:47.427+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:50:47.428+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:50:47.427+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:50:47.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:50:47.437+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T16:51:43.322+0000] {processor.py:161} INFO - Started process (PID=1157) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:51:43.324+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:51:43.325+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:51:43.324+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:51:43.330+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:51:43.330+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:51:43.330+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:51:43.330+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:51:43.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:51:43.341+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T16:52:39.682+0000] {processor.py:161} INFO - Started process (PID=1235) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:52:39.684+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:52:39.685+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:52:39.685+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:52:39.691+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:52:39.690+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:52:39.691+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:52:39.691+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:52:39.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:52:39.702+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-11T16:53:32.270+0000] {processor.py:161} INFO - Started process (PID=1303) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:53:32.272+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:53:32.273+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:53:32.272+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:53:32.278+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:53:32.277+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:53:32.278+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:53:32.278+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:53:32.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:53:32.288+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T16:54:26.758+0000] {processor.py:161} INFO - Started process (PID=1368) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:54:26.760+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:54:26.761+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:54:26.760+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:54:26.766+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:54:26.766+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:54:26.766+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:54:26.766+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:54:26.767+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:54:26.777+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-11T16:55:22.000+0000] {processor.py:161} INFO - Started process (PID=1444) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:55:22.003+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:55:22.004+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:55:22.003+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:55:22.009+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:55:22.008+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:55:22.009+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:55:22.009+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:55:22.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:55:22.020+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-11T16:56:13.687+0000] {processor.py:161} INFO - Started process (PID=1513) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:56:13.689+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:56:13.690+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:56:13.690+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:56:13.696+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:56:13.695+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:56:13.696+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:56:13.696+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:56:13.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:56:13.707+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-11T16:57:05.895+0000] {processor.py:161} INFO - Started process (PID=1598) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:57:05.897+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:57:05.898+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:57:05.898+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:57:05.903+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:57:05.903+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:57:05.904+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:57:05.904+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:57:05.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:57:05.914+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T16:58:01.603+0000] {processor.py:161} INFO - Started process (PID=1770) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:58:01.605+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T16:58:01.606+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:58:01.606+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:58:01.611+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:58:01.611+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T16:58:01.611+0000] {logging_mixin.py:188} INFO - [2024-03-11T16:58:01.611+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T16:58:01.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T16:58:01.621+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T17:07:20.263+0000] {processor.py:161} INFO - Started process (PID=2099) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:07:20.266+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T17:07:20.267+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:07:20.267+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:07:20.271+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:07:20.270+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T17:07:20.271+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:07:20.271+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T17:07:20.271+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:07:20.282+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-11T17:08:44.696+0000] {processor.py:161} INFO - Started process (PID=2255) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:08:44.698+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T17:08:44.699+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:08:44.698+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:08:44.701+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:08:44.701+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T17:08:44.702+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:08:44.702+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T17:08:44.702+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:08:44.710+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-03-11T17:09:43.062+0000] {processor.py:161} INFO - Started process (PID=2393) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:09:43.064+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T17:09:43.065+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:09:43.065+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:09:43.069+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:09:43.068+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T17:09:43.069+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:09:43.069+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T17:09:43.069+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:09:43.078+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-03-11T17:10:41.155+0000] {processor.py:161} INFO - Started process (PID=2471) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:10:41.157+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T17:10:41.158+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:10:41.157+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:10:41.161+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:10:41.161+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T17:10:41.162+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:10:41.162+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T17:10:41.162+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:10:41.172+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T17:12:02.421+0000] {processor.py:161} INFO - Started process (PID=2579) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:12:02.423+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T17:12:02.424+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:12:02.424+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:12:02.428+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:12:02.427+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T17:12:02.428+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:12:02.428+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T17:12:02.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:12:02.439+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T17:13:00.614+0000] {processor.py:161} INFO - Started process (PID=2657) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:13:00.616+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T17:13:00.617+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:13:00.616+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:13:00.620+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:13:00.620+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T17:13:00.621+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:13:00.621+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T17:13:00.621+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:13:00.631+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T17:13:56.210+0000] {processor.py:161} INFO - Started process (PID=2778) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:13:56.213+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T17:13:56.214+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:13:56.213+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:13:56.217+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:13:56.217+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T17:13:56.217+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:13:56.217+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T17:13:56.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:13:56.228+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T17:15:15.238+0000] {processor.py:161} INFO - Started process (PID=2930) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:15:15.240+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T17:15:15.241+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:15:15.240+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:15:15.244+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:15:15.244+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T17:15:15.244+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:15:15.244+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T17:15:15.245+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:15:15.255+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-03-11T17:16:10.162+0000] {processor.py:161} INFO - Started process (PID=3008) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:16:10.164+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T17:16:10.165+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:16:10.165+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:16:10.169+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:16:10.168+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T17:16:10.169+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:16:10.169+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T17:16:10.170+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:16:10.180+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T17:17:03.697+0000] {processor.py:161} INFO - Started process (PID=3072) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:17:03.699+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T17:17:03.700+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:17:03.700+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:17:03.704+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:17:03.703+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T17:17:03.704+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:17:03.704+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T17:17:03.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:17:03.714+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-03-11T17:18:00.058+0000] {processor.py:161} INFO - Started process (PID=3143) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:18:00.060+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T17:18:00.061+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:18:00.061+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:18:00.065+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:18:00.065+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T17:18:00.065+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:18:00.065+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T17:18:00.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:18:00.076+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T17:18:54.554+0000] {processor.py:161} INFO - Started process (PID=3219) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:18:54.557+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T17:18:54.558+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:18:54.557+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:18:54.561+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:18:54.561+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T17:18:54.561+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:18:54.561+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T17:18:54.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:18:54.572+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T17:19:48.470+0000] {processor.py:161} INFO - Started process (PID=3284) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:19:48.472+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T17:19:48.473+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:19:48.472+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:19:48.476+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:19:48.476+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T17:19:48.476+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:19:48.476+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T17:19:48.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:19:48.486+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-03-11T17:20:42.978+0000] {processor.py:161} INFO - Started process (PID=3353) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:20:42.980+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T17:20:42.981+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:20:42.980+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:20:42.984+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:20:42.984+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T17:20:42.985+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:20:42.985+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T17:20:42.985+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:20:42.995+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-11T17:21:35.059+0000] {processor.py:161} INFO - Started process (PID=3429) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:21:35.061+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-11T17:21:35.062+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:21:35.062+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:21:35.066+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:21:35.066+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-11T17:21:35.066+0000] {logging_mixin.py:188} INFO - [2024-03-11T17:21:35.066+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-11T17:21:35.067+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-11T17:21:35.077+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
