[2024-03-11T17:02:03.083+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: Lead_scoring_training_pipeline.training_model manual__2024-03-11T16:59:39.940041+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
